# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydocker < Formula
  desc "A simple terminal UI for docker, written in Go"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "0.25.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_darwin_amd64.tar.gz"
      sha256 "f880717aeb90a4217cb60a29b42fb357ae4f81b56c2306d54567572020bbc043"

      define_method(:install) do
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_darwin_arm64.tar.gz"
      sha256 "356ea1124eafb779ac0e43a9743a0023a4732edf63cdcff917c82f99479bc315"

      define_method(:install) do
        bin.install "lazydocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_linux_amd64.tar.gz"
      sha256 "7a2cf711c302ebd9422c3160f701f826c32cbeda2bffaeadc4f38edd3cc42431"
      define_method(:install) do
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_linux_armv6.tar.gz"
      sha256 "3fc127e4e0cc424722a979173bae4d383fb8309f453d9332ad82fa69fcbecfd6"
      define_method(:install) do
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_linux_arm64.tar.gz"
      sha256 "1eacf45190a5875f1ab2f873335bb26a52e54020fef92cd55c3e25327d087dd1"
      define_method(:install) do
        bin.install "lazydocker"
      end
    end
  end
end
