# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autossh < Formula
  desc "A simple ssh connection manager, written in Go"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.1/autossh_1.2.1_darwin_amd64.tar.gz"
      sha256 "41d8535ef87e542143ad367463faf27fcbf4d0372f3de5e70d4a61837eec159f"

      define_method(:install) do
        bin.install "autossh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.1/autossh_1.2.1_darwin_arm64.tar.gz"
      sha256 "0fbf17c10321039393bad2a6ef8e0819b7d01dc374daec3f50b38ddf2236c8c6"

      define_method(:install) do
        bin.install "autossh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.1/autossh_1.2.1_linux_amd64.tar.gz"
      sha256 "80fe34f5285dd10eaa544863f88007dedb653c1e9edab625ff587595b005ceba"
      define_method(:install) do
        bin.install "autossh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.1/autossh_1.2.1_linux_armv6.tar.gz"
      sha256 "dd2fa565f214eba86198dc79f52c2c6621d7a21ab8f311f6421c521b906211b8"
      define_method(:install) do
        bin.install "autossh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.1/autossh_1.2.1_linux_arm64.tar.gz"
      sha256 "f91c33726118f5b512bce9c53ce18df579a47d161fa125f32e678d94fe3b25be"
      define_method(:install) do
        bin.install "autossh"
      end
    end
  end
end
