# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autossh < Formula
  desc "A simple ssh connection manager, written in Go"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "1.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.5/autossh_1.2.5_darwin_amd64.tar.gz"
      sha256 "9bbd92688fd553dd5d46c62ddd17562037760dd7ad7228429c07b06d686b9c77"

      define_method(:install) do
        bin.install "autossh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.5/autossh_1.2.5_darwin_arm64.tar.gz"
      sha256 "25a3b7c6177a8d7ef4629193b6cc799cd6cfb1282bbc1730be162ddd9d6de2e1"

      define_method(:install) do
        bin.install "autossh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.5/autossh_1.2.5_linux_amd64.tar.gz"
      sha256 "b094a615fcf51ec451f3dfa5b1723de1f35374e698a5fcdf616d25674774a0d1"
      define_method(:install) do
        bin.install "autossh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.5/autossh_1.2.5_linux_armv6.tar.gz"
      sha256 "8cb33bccb5b93c7bd383f155368c66f29fa161161efbccd0f5f5c77eaa4e7ee1"
      define_method(:install) do
        bin.install "autossh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/autossh/releases/download/v1.2.5/autossh_1.2.5_linux_arm64.tar.gz"
      sha256 "94b43934a4e6bdf923bba066c266c4d7710a4440bd839432c6232c3f71960c16"
      define_method(:install) do
        bin.install "autossh"
      end
    end
  end
end
