# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcli < Formula
  desc "A simple terminal UI for docker, written in Go"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.0/dcli_0.1.0_darwin_amd64.tar.gz"
      sha256 "a30be28573cabf8f4f77c3f05ca4787923da4251d57513449676fc21b376963e"

      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.0/dcli_0.1.0_darwin_arm64.tar.gz"
      sha256 "b8cbb672dac3ae901e1e3660db2b803a9582aa215b8d0a58216c56ed7dc3b25a"

      define_method(:install) do
        bin.install "dcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.0/dcli_0.1.0_linux_amd64.tar.gz"
      sha256 "b5b97d1ac602d9e769b3eb12c7e0f5791326cca97d38c6fc95b78cba820b94ae"
      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.0/dcli_0.1.0_linux_armv6.tar.gz"
      sha256 "e09859ed999e848f4fd6fe49c78d29b8c537a14e989e1f257faada9c56ad379d"
      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.0/dcli_0.1.0_linux_arm64.tar.gz"
      sha256 "3b0e54cfe6c5370a412d6072cdf6e8641de7cf4c7dff6eb3df2fcc3b5e803296"
      define_method(:install) do
        bin.install "dcli"
      end
    end
  end
end
