# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcli < Formula
  desc "A simple terminal UI for docker, written in Go"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.1/dcli_0.1.1_darwin_amd64.tar.gz"
      sha256 "59b30f55e5aba8d6f950b3d7c54e4f3ba377f48b9a1655d899c8215416fe2afd"

      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.1/dcli_0.1.1_darwin_arm64.tar.gz"
      sha256 "945857235140c7c910923d2cd9aa28d0323a1b6b9bce190715119e70bf1b7e42"

      define_method(:install) do
        bin.install "dcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.1/dcli_0.1.1_linux_amd64.tar.gz"
      sha256 "8ce30828b385b2cf3ab5c2a6873d5020fcf61eeffb2952efe016fd28620730db"
      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.1/dcli_0.1.1_linux_armv6.tar.gz"
      sha256 "cf1a63e773a6814f53b21be56103127ba02f1fafcdac8589da55d2ed530b6700"
      define_method(:install) do
        bin.install "dcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/dcli/releases/download/v0.1.1/dcli_0.1.1_linux_arm64.tar.gz"
      sha256 "b36d06cdf5d13dda22a9cda699e4f4e56b985e7c1f06e5ee208236192390feb9"
      define_method(:install) do
        bin.install "dcli"
      end
    end
  end
end
