# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydocker < Formula
  desc "A simple terminal UI for docker, written in Go"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "0.25.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_darwin_amd64.tar.gz"
      sha256 "0fe964b91d670cb3b7fb53bb17f21ddd980a9d0eae37c400b86cf934437a26bb"

      define_method(:install) do
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_darwin_arm64.tar.gz"
      sha256 "6c5ef3b70681f642dcfb124ed684c325c848929596659b25b9450ef4f6b820e6"

      define_method(:install) do
        bin.install "lazydocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_linux_amd64.tar.gz"
      sha256 "376aa8940828056bcbea9e14da2cdcb8df2b77b0414fac8f3340088204d08f36"
      define_method(:install) do
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_linux_armv6.tar.gz"
      sha256 "43493feda226a3875a8594fec6b6dff2a1974fe4a3dd87395ad6d757d3178be8"
      define_method(:install) do
        bin.install "lazydocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/lazydocker/releases/download/v0.25.2/lazydocker_0.25.2_linux_arm64.tar.gz"
      sha256 "b09707328ddf9d6ca25210e708d2c1d267685e3d640eb3421bef081629612a04"
      define_method(:install) do
        bin.install "lazydocker"
      end
    end
  end
end
