# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdcli < Formula
  desc "A high-efficiency, minimalist CLI for Markdown preview and management"
  homepage "https://github.com/yaogh99123/homebrew-tap/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaogh99123/mdcli/releases/download/v0.1.0/mdcli_0.1.0_darwin_amd64.tar.gz"
      sha256 "a79a8f7c6cdfcc645d305c1e6a987b1b0186ecea3061ec807de24457ef120d77"

      define_method(:install) do
        bin.install "mdcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaogh99123/mdcli/releases/download/v0.1.0/mdcli_0.1.0_darwin_arm64.tar.gz"
      sha256 "f1c9fd6fc84beb14936d9bb79ec9a9dc906c95fd9dc977875dafdfe151dc96fe"

      define_method(:install) do
        bin.install "mdcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/mdcli/releases/download/v0.1.0/mdcli_0.1.0_linux_amd64.tar.gz"
      sha256 "f987d56314f5cd63a5dc2dd61934fa03589cd01277da6cf5431f50a0eee5ca06"
      define_method(:install) do
        bin.install "mdcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/mdcli/releases/download/v0.1.0/mdcli_0.1.0_linux_armv6.tar.gz"
      sha256 "ce33e007ebcf0b443b6f1056580a7fe6d9fd93e99fdf8721f493a907a903f5e3"
      define_method(:install) do
        bin.install "mdcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaogh99123/mdcli/releases/download/v0.1.0/mdcli_0.1.0_linux_arm64.tar.gz"
      sha256 "8aaa874bb8d6484fdc6eb083c20a7063886f7866d45a3bf2de05a86aed67e693"
      define_method(:install) do
        bin.install "mdcli"
      end
    end
  end
end
